apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: python-arfjdmss
  janus-idp.io/tekton: python-arfjdmss
  backstage.io/kubernetes-id: python-arfjdmss
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: python-arfjdmss
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
